
ascii_map = {
    r"\x0c01" : "(Start of heading)",
    r"\x0c02" : "(Start of text)",
    r"\x0c03" : "(End of text) (see: UNIX keyboard CTRL)",
    r"\x0c04" : "(End of transmission) (see: UNIX keyboard CTRL)",
    r"\x0c05" : "(Enquiry)",
    r"\x0c06" : "(Acknowledge)",
    r"\x0c07" : "(Ring terminal bell)",
    r"\x0c08" : "(Backspace)  (\b matches backspace inside [] only)",
    r"\xe2" : "'",
    r"\x0ce2" : "'",

    r"\x0c09" : "\t",
    r"\x0c0A" : "\n",
    r"\x0c0B" : "(Vertical tab)",
    r"\x0c0C" : "\f",
    r"\x0c0D" : "\r",
    r"\x0c0E" : "(Shift out)",
    r"\x0c0F" : "(Shift in)",
    r"\x0c10" : "(Data link escape)",
    r"\x0c11" : "(Device control 1) (XON) (Default UNIX START char.)",
    r"\x0c12" : "(Device control 2)",
    r"\x0c13" : "(Device control 3) (XOFF)  (Default UNIX STOP char.)",
    r"\x0c14" : "(Device control 4)",
    r"\x0c15" : "(Negative acknowledge)  (see: UNIX keyboard CTRL)",
    r"\x0c16" : "(Synchronous idle)",
    r"\x0c17" : "(End of transmission block)",
    r"\x0c18" : "(Cancel)",
    r"\x0c19" : "(End of medium)",
    r"\x0c1A" : "(Substitute character)",
    r"\x0c1B" : "(Escape)",
    r"\x0c1C" : "(File separator, Information separator four)",
    r"\x0c1D" : "(Group separator, Information separator three)",
    r"\x0c1E" : "(Record separator, Information separator two)",
    r"\x0c1F" : "(Unit separator, Information separator one)",
    r"\x0c7F" : "(Delete)  (see: UNIX keyboard CTRL)",

    r"\x0c20" :             "(space)",
    r"\x0c21" :  "EXCLAMATION POINT(bang)",
    r"\x0c22" :  "QUOTATION MARK, DIAERESIS",
    r"\x0c23" :  "NUMBER SIGN (Pound sign) (see: UNIX keyboard CTRL)",
    r"\x0c24" :  "DOLLAR SIGN",
    r"\x0c25" :  "PERCENT SIGN",
    r"\x0c26" :  "AMPERSAND",
    r"\x0c27" :  "APOSTROPHE, RIGHT SINGLE QUOTATION MARK, ACUTE ACCENT (single quote)",
    r"\x0c28" :  "LEFT PARENTHESIS  (open parenthesis)",
    r"\x0c29" :  "RIGHT PARENTHESIS (close parenthesis)",
    r"\x0c2A" :  "ASTERISK",
    r"\x0c2B" :  "PLUS SIGN",
    r"\x0c2C" :  "COMMA, CEDILLA",
    r"\x0c2D" :  "HYPHEN, MINUS SIGN",
    r"\x0c2E" :  "PERIOD, DECIMAL POINT, (Full Stop)",
    r"\x0c2F" :  "SLANT (SOLIDUS), slash",

    r"\x0c3A" :   "COLON",
    r"\x0c3B" :   "SEMICOLON",
    r"\x0c3C" :   "LESS-THAN SIGN  (left angle bracket)",
    r"\x0c3D" :   "EQUALS SIGN",
    r"\x0c3E" :   "GREATER-THAN SIGN  (right angle bracket)",
    r"\x0c3F" :   "QUESTION MARK",
    r"\x0c40" :   "COMMERCIAL AT  (see: UNIX keyboard CTRL)",

    r"\x0c5B" :  "LEFT (SQUARE) BRACKET (open bracket)",
    r"\x0c5C" :   "REVERSE SLANT (REVERSE SOLIDUS) (backslash, backslant)",
    r"\x0c5D" :   "RIGHT (SQUARE) BRACKET (closing bracket)",
    r"\x0c5E" :   "CIRCUMFLEX ACCENT",
    r"\x0c5F" :   "UNDERLINE (LOW LINE)",
    r"\x0c60" :   "LEFT SINGLE QUOTATION MARK, GRAVE ACCENT",

    r"\x0c7B" : "LEFT BRACE (LEFT CURLY BRACKET) (open brace) ",
    r"\x0c7C" : "VERTICAL LINE (pipe) ",
    r"\x0c7D" : "RIGHT BRACE (RIGHT CURLY BRACKET) (closing brace) ",
    r"\x0c7E" : "TILDE (OVERLINE) (squiggle) "
}